---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        imagePullPolicy: Always
        image: hasannaber123/monitoring:latest
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: GIN_MODE
          value: release
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
  namespace: staging
  labels:
    app: go-server
spec:
  selector:
    app: go-server
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: staging
spec:
  ingressClassName: external-ingress-nginx
  rules:
    - host: ilovek8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-server
                port:
                  number: 8080
